name: Build and Extract Executable

on:
  push:
    branches:
      - main  # 或者是你想要触发构建的分支

jobs:
  build-and-extract:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        platforms: linux/arm64
        load: true
        tags: myapp:latest

    - name: Create Container from Image
      id: create_container
      run: |
        echo "Creating Container..."
        id=$(docker create myapp:latest)
        echo "::set-output name=id::$id"

    - name: Copy Executable from Container
      run: |
        docker cp ${{ steps.create_container.outputs.id }}:/app/dist/ShuSDDNS ./ShuSDDNS

    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ShuSDDNS-executable
        path: ./ShuSDDNS
