name: Build Python Application for aarch64

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and export Python application
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        platforms: linux/arm64
        load: true
        tags: username/myapp:aarch64
        file: Dockerfile

    - name: Extract the compiled application
      run: |
        id=$(docker create username/myapp:aarch64)
        docker cp $id:/path/to/dist/ShuSDDNS ./
        docker rm -v $id

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ShuSDDNS-aarch64
        path: ShuSDDNS
